// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4o52l8BCTxzxhm04gmipUumF_ShmIU5g',
    appId: '1:134849275185:web:768fa221bed21e36dfbc10',
    messagingSenderId: '134849275185',
    projectId: 'flutterfirebase-12212',
    authDomain: 'flutterfirebase-12212.firebaseapp.com',
    storageBucket: 'flutterfirebase-12212.appspot.com',
    measurementId: 'G-Q2JMJDL0JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2B3-feyAl17lRnDUH5ueYfEdBGp6xmEU',
    appId: '1:134849275185:android:8e6fab5ad7fd4bdcdfbc10',
    messagingSenderId: '134849275185',
    projectId: 'flutterfirebase-12212',
    storageBucket: 'flutterfirebase-12212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA79D4_LpIHlKg3Lkey88936DDD9rS1EHA',
    appId: '1:134849275185:ios:7e90cd24c51ba314dfbc10',
    messagingSenderId: '134849275185',
    projectId: 'flutterfirebase-12212',
    storageBucket: 'flutterfirebase-12212.appspot.com',
    iosClientId: '134849275185-hddsjdrj6eaghbg1b26oeht8dhnbu292.apps.googleusercontent.com',
    iosBundleId: 'com.example.avinutri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA79D4_LpIHlKg3Lkey88936DDD9rS1EHA',
    appId: '1:134849275185:ios:ac969ea67827aac5dfbc10',
    messagingSenderId: '134849275185',
    projectId: 'flutterfirebase-12212',
    storageBucket: 'flutterfirebase-12212.appspot.com',
    iosClientId: '134849275185-vccuivhj8cae3rjd4ieh7f0h842oh1mj.apps.googleusercontent.com',
    iosBundleId: 'com.example.avinutri.RunnerTests',
  );
}
